name: test config var

on:
  workflow_dispatch:

env:
  PROJECT: ${{ vars.PROJECT_NAME }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print vars
        run: echo "Project: $PROJECT"